### PR TITLE
Same as MahHairy Posts and Comments#72

### PR DESCRIPTION
**Pull request by giroux2000**
Created a new branch instead of rebasing code. Can now follow users and have it displayed on the webpage

### CODE REVIEW

**Review by halloweentown — APPROVED** [review]
Architecture documentation updated to match
- closes #73

Verified the following are functional:
- closes #59 
- closes #13  

Travis CI Build error seems to be caused by a lack of support for new Laravel Framework 4.1.X. 
@MahHairy can you look into this?

**Comment by maherysm** [comment]
> Travis CI Build error seems to be caused by a lack of support for new Laravel Framework 4.1.X.
> @MahHairy can you look into this?

Duplicate requirements on the composer.json file was causing the errors on Travis-CI. Therefore, they had to be removed.
image

**Review by r-vaidya — APPROVED** [review]
Core feature "Follow" now works

**Review by j-loy — APPROVED** [review]
Noted some Styling changes with added functionalitiies

**Review by maherysm — APPROVED** [review]
All features and Travis CI are functional

**Pull request merged**
