### PR TITLE
Sprint 2 Demo Code

### PR DESCRIPTION
**Pull request by halloweentown**
This merge includes the Sprint 2 back end features to be demonstrated.
All other branches must rebase using this.

### CODE REVIEW

**Review by giroux2000 — APPROVED** [review]
I wrote this, it works

**Comment by halloweentown** [comment]
Merge of React front caused back end to fail. Please rebase using this.

**Review by j-loy — APPROVED** [review]
Demo code to show for tomorrow

**Review by r-vaidya — APPROVED** [review]
ready demo for sprint 2

**Pull request merged**
