### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by halloweentown**
Update languages used, design documentation

### CODE REVIEW

**Review by r-vaidya — APPROVED** [review]
Updated Readme includes all changes up until Sprint 3

**Review by CSman22 — APPROVED** [review]
Seems to be alright to me.

**Comment by giroux2000** [comment]
Changes reflect the changes in our project. Great work team!

**Review by j-loy — APPROVED** [review]
Updated readme according to project specification and updates

**Comment by parker-1212** [comment]
good job guys!

**Pull request merged**
