### PR TITLE
Adding Project Description to Readme

### LINKED ISSUE #2: Create and Update the readme.md [2]
- [x] the info of your team members (real name and GitHub user name)
- [x] what languages & techniques do you plan to use (if haven't decided, then write sth like TBD)

### PR DESCRIPTION
**Pull request by r-vaidya**
- Tentative Project Description

### CODE REVIEW

**Review by halloweentown — CHANGES_REQUESTED** [review]
Pull from main and then add your changes

**Review by halloweentown — APPROVED** [review]
Changes reflect meeting minutes.

**Review by giroux2000 — APPROVED** [review]
Summary of what was discussed during the meeting.

**Review by j-loy — APPROVED** [review]
Description and Techniques added

**Review by r-vaidya — COMMENTED** [review]
Added Front End and Back end Languages(Tentative)

**Review by r-vaidya — COMMENTED** [review]
Added Description for Project

**Comment by r-vaidya** [comment]
Updated the Readme file by adding a description for the SOEN341 project and adding the planned languages that will be used under the corresponding heading

**Pull request merged**
