### PR TITLE
Design Documentation

### LINKED ISSUE #73: [PM-02] Identify ideal architecture pattern, document the proposed architecture design [5]
### **Functional Requirements**

- [x] 1 The architecture pattern used by our chosen framework is identified, understood, and confirmed to be appropriate given other User Stories.
- [x] 2 Important elements of framework are clearly identified and understood
- [x] 3 Interactions between said elements are clearly identified and understood

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [x] Architecture pattern identified
- [x] Documentation created
- [x] Per pattern, diagram contains all required elements (ex: Models, views, controllers)
- [x] Interactions between elements clearly labelled

### PR DESCRIPTION
**Pull request by halloweentown**
- Architecture diagram: Model View Controller
- Relational Database Design
Closes #73

### CODE REVIEW

**Review by maherysm — APPROVED** [review]
- successful rebasing of this branch onto main
- main models, controllers and views (with main methods) from Laravel are present
- _Following_ controller details will be changed later on

**Review by maherysm — CHANGES_REQUESTED** [review]
- Updating Following controller methods 
image
- Updating User model methods 
image
- Updating User model attributes 
image
- Updating Post model attributes 
image
- Updating Comment model attributes 
image

**Review by j-loy — APPROVED** [review]
Design Documentation Done

**Comment by halloweentown** [comment]
> * Updating Following controller methods
>   image
> * Updating User model methods
>   image
> * Updating User model attributes
>   image
> * Updating Post model attributes
>   image
> * Updating Comment model attributes
>   image

Updated accordingly

**Review by maherysm — APPROVED** [review]

**Pull request merged**
